import type { Metadata } from "next";
import Sidebar from "@/components/sidebar/Sidebar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen w-screen bg-[#2E2F38] flex">
          <div className="bg-[#25262D] flex-2 p-3">
            <Sidebar />
          </div>

          <div className="flex flex-8">{children}</div>
        </div>
      </body>
    </html>
  );
}
